#!/usr/bin/env bash
# PreToolUse(Bash): block `git commit` commands that carry an AI-authorship footer.
# Deterministic enforcement of the anti-ai skill's git-commit rule. Exit 2 = block,
# stderr is fed back to Claude so it can recommit without the footer.
# ponytail: greps the raw event JSON instead of parsing it, so no jq/python dependency.
input=$(cat)

# Only act on git commit calls (avoids false positives on, e.g., grepping for these strings).
printf '%s' "$input" | grep -qiE 'git commit' || exit 0

printf '%s' "$input" | grep -qiE 'co-authored-by:[^"\\]*claude|noreply@anthropic\.com|generated with \[?claude|generated by claude|🤖' || exit 0

echo "anti-ai: this git commit carries an AI-authorship footer (Co-Authored-By: Claude / Generated with Claude / noreply@anthropic.com). Strip the footer and commit again — the user is the sole author. Only keep it if the user explicitly asked for a co-author trailer." >&2
exit 2
